# Generated by Django 3.2.8 on 2022-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('5', '5️⃣'), ('6', '6️⃣'), ('4', '4️⃣'), ('9', '9️⃣'), ('7', '7️⃣'), ('3', '3️⃣'), ('1', '1️⃣'), ('8', '8️⃣'), ('2', '2️⃣'), ('10', '🔟')], max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETED')], max_length=2),
        ),
    ]
